---
- name: Playbook to update saltshaker servers
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - ./secrets.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - name: Copy salt master configs
      copy:
        src: "./configs/"
        dest: "/etc/salt/master.d/"
        force: false

    - name: Copy server config
      template:
        src: ./scripts/server.conf.j2
        dest: /etc/salt/master.d/server.conf
        force: false

    - name: Update minion of salt for syndic fix
      template:
        src: ./scripts/minion.py
        dest: /usr/lib/python3/dist-packages/salt/minion.py

    - name: Copy certificate zip
      debug:
        msg: "cert_name for {{ inventory_hostname }} is {{ hostvars[inventory_hostname].cert_name }}"

    - name: Set permissions on /srv folder
      file:
        path: /srv
        state: directory
        mode: "0777"

    - name: Clone Saltshaker repository
      git:
        repo: git@github.bus.zalan.do:whit-berlin/zalando-saltshaker.git
        dest: /srv/saltshaker/
        version: develop
        accept_hostkey: yes
      become: false

    - name: Clone Salt repository
      git:
        repo: git@github.bus.zalan.do:whit-berlin/salt.git
        dest: /srv/salt/
        version: main
        accept_hostkey: yes
      become: false

    - name: Update saltshaker location settings
      template:
        src: ./scripts/location.js.j2
        dest: /srv/saltshaker/static/location.js

    - name: Restart services
      block:
        - name: Restart salt-minion
          service:
            name: salt-minion
            state: restarted

        - name: Restart salt-master
          service:
            name: salt-master
            state: restarted

        - name: Restart salt-syndic
          service:
            name: salt-syndic
            state: restarted

        - name: Restart salt-api
          service:
            name: salt-api
            state: restarted
