---
- name: Playbook to update salt state configs
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - ./secrets.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - name: Clone Salt repository
      git:
        repo: git@github.bus.zalan.do:whit-berlin/salt.git
        dest: /srv/salt/
        version: main
        accept_hostkey: yes
        recursive: yes
        update: yes
        force: yes
      become: false
